### ISSUE TITLE
Update documentation on how to use plugin

### ISSUE THREAD

**Issue by mudnaes** [crealitycloud/CrealityCloudIntegration#1]
**Is your feature request related to a problem? Please describe.**
Most cura plugins are used from extension menu. This plugin is only visible when saving gcode after slicing. 

**Describe the solution you'd like**
Please update documentation on how to use this plugin. Also include how to find you model on mobile app after upload.

Anyway great work making a plugin to do upload from inside cura. Very useful!

**Comment by frank-pian** [comment]
https://www.crealitycloud.com/post-detail/3362
