### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by docimin** [crealitycloud/CrealityCloudIntegration#2]
The whole plugin does not work anymore as it should. Not on marketplace either.
Cura 5.0 asks you to delete the plugin because it will not start.

**Comment by cookopotamus** [comment]
I think they need to update and put up a new version for Cura 5.0, which they should... I +1 that idea.

**Comment by efekthalo** [comment]
all you need to do is download the plugin from GitHub, drag and drop the file in Cura and the plugin works just fine

tested with Cura 5.0.0

**Comment by hemiao218** [comment]
u

**Comment by docimin** [comment]
> all you need to do is download the plugin from GitHub, drag and drop the file in Cura and the plugin works just fine
> 
> 
> 
> tested with Cura 5.0.0

Bruh, this comment was so unnecessary, it was towards the devs when they didn't update it yet.
Next time fact-check before you post.
